export default {
  TAMPA: {
    ADDRESS: '0x1294d9b2129ddae270AD572eA1bdA42aB48acb34',
    SYMBOL: 'JETH',
    DECIMALS: 8,
    ABI: [
      {
        type: 'constructor',
        stateMutability: 'nonpayable',
        payable: false,
        inputs: [
          { type: 'uint256', name: '_LAUNCH_TIME', internalType: 'uint256' },
          { type: 'uint256', name: '_dayNumberBegin', internalType: 'uint256' },
          { type: 'uint256', name: '_ROUND_TIME', internalType: 'uint256' },
          {
            type: 'uint256',
            name: '_LOTERY_ENTRY_TIME',
            internalType: 'uint256',
          },
        ],
      },
      {
        type: 'event',
        name: 'Approval',
        inputs: [
          {
            type: 'address',
            name: 'owner',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'address',
            name: 'spender',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'value',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'DailyDataUpdate',
        inputs: [
          {
            type: 'address',
            name: 'updaterAddr',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'beginDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'endDay',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'OwnershipTransferred',
        inputs: [
          {
            type: 'address',
            name: 'previousOwner',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'address',
            name: 'newOwner',
            internalType: 'address',
            indexed: true,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'ShareRateChange',
        inputs: [
          {
            type: 'uint40',
            name: 'stakeId',
            internalType: 'uint40',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'newShareRate',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'StakeEnd',
        inputs: [
          {
            type: 'uint40',
            name: 'stakeId',
            internalType: 'uint40',
            indexed: true,
          },
          {
            type: 'uint40',
            name: 'prevUnlocked',
            internalType: 'uint40',
            indexed: false,
          },
          {
            type: 'address',
            name: 'stakerAddr',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'lockedDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'servedDays',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakedSuns',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakeShares',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'payout',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'penalty',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakeReturn',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'StakeGoodAccounting',
        inputs: [
          {
            type: 'uint40',
            name: 'stakeId',
            internalType: 'uint40',
            indexed: true,
          },
          {
            type: 'address',
            name: 'stakerAddr',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'address',
            name: 'senderAddr',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'stakedSuns',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakeShares',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'payout',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'penalty',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'StakeStart',
        inputs: [
          {
            type: 'uint40',
            name: 'stakeId',
            internalType: 'uint40',
            indexed: true,
          },
          {
            type: 'address',
            name: 'stakerAddr',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'stakedSuns',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakeShares',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'stakedDays',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'Transfer',
        inputs: [
          {
            type: 'address',
            name: 'from',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'address',
            name: 'to',
            internalType: 'address',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'value',
            internalType: 'uint256',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'XfLobbyEnter',
        inputs: [
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'enterDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'entryIndex',
            internalType: 'uint256',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'rawAmount',
            internalType: 'uint256',
            indexed: true,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'XfLobbyExit',
        inputs: [
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'enterDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'entryIndex',
            internalType: 'uint256',
            indexed: true,
          },
          {
            type: 'uint256',
            name: 'xfAmount',
            internalType: 'uint256',
            indexed: true,
          },
          {
            type: 'address',
            name: 'referrerAddr',
            internalType: 'address',
            indexed: true,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'loteryLobbyEnter',
        inputs: [
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'enterDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'rawAmount',
            internalType: 'uint256',
            indexed: true,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'loteryLobbyExit',
        inputs: [
          {
            type: 'uint256',
            name: 'timestamp',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'enterDay',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'rawAmount',
            internalType: 'uint256',
            indexed: true,
          },
        ],
        anonymous: false,
      },
      {
        type: 'event',
        name: 'loteryWin',
        inputs: [
          {
            type: 'uint256',
            name: 'day',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'uint256',
            name: 'amount',
            internalType: 'uint256',
            indexed: false,
          },
          {
            type: 'address',
            name: 'who',
            internalType: 'address',
            indexed: false,
          },
        ],
        anonymous: false,
      },
      { type: 'fallback', stateMutability: 'payable', payable: true },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'LAUNCH_TIME',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'LOTERY_ENTRY_TIME',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'ROUND_TIME',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'allocatedSupply',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'allowance',
        inputs: [
          { type: 'address', name: 'owner', internalType: 'address' },
          { type: 'address', name: 'spender', internalType: 'address' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
        name: 'approve',
        inputs: [
          { type: 'address', name: 'spender', internalType: 'address' },
          { type: 'uint256', name: 'amount', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'balanceOf',
        inputs: [{ type: 'address', name: 'account', internalType: 'address' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: 'payout', internalType: 'uint256' }],
        name: 'calcPayoutDividendsReward',
        inputs: [
          {
            type: 'uint256',
            name: 'stakeSharesParam',
            internalType: 'uint256',
          },
          { type: 'uint256', name: 'beginDay', internalType: 'uint256' },
          { type: 'uint256', name: 'endDay', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: 'payout', internalType: 'uint256' }],
        name: 'calcPayoutRewards',
        inputs: [
          {
            type: 'uint256',
            name: 'stakeSharesParam',
            internalType: 'uint256',
          },
          { type: 'uint256', name: 'beginDay', internalType: 'uint256' },
          { type: 'uint256', name: 'endDay', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: 'payout', internalType: 'uint256' }],
        name: 'calcPayoutRewardsBonusDays',
        inputs: [
          {
            type: 'uint256',
            name: 'stakeSharesParam',
            internalType: 'uint256',
          },
          { type: 'uint256', name: 'beginDay', internalType: 'uint256' },
          { type: 'uint256', name: 'endDay', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'currentDay',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256', name: 'dayPayoutTotal', internalType: 'uint256' },
          { type: 'uint256', name: 'dayDividends', internalType: 'uint256' },
          {
            type: 'uint256',
            name: 'dayStakeSharesTotal',
            internalType: 'uint256',
          },
        ],
        name: 'dailyData',
        inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'dailyDataUpdate',
        inputs: [
          { type: 'uint256', name: 'beforeDay', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'dayChanceCount',
        inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'dayNumberBegin',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint8', name: '', internalType: 'uint8' }],
        name: 'decimals',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'address', name: '', internalType: 'address' }],
        name: 'defaultReferrerAddr',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'endLoteryDay',
        inputs: [{ type: 'uint256', name: 'endDay', internalType: 'uint256' }],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'endedStakeCount',
        inputs: [
          { type: 'address', name: 'stakerAddr', internalType: 'address' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint40', name: 'stakeId', internalType: 'uint40' },
          { type: 'uint256', name: 'stakedSuns', internalType: 'uint256' },
          { type: 'uint256', name: 'stakeShares', internalType: 'uint256' },
          { type: 'uint16', name: 'lockedDay', internalType: 'uint16' },
          { type: 'uint16', name: 'stakedDays', internalType: 'uint16' },
          { type: 'uint16', name: 'unlockedDay', internalType: 'uint16' },
          { type: 'uint256', name: 'unstakePayout', internalType: 'uint256' },
          {
            type: 'uint256',
            name: 'unstakeDividends',
            internalType: 'uint256',
          },
        ],
        name: 'endedStakeLists',
        inputs: [
          { type: 'address', name: '', internalType: 'address' },
          { type: 'uint256', name: '', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'address', name: '', internalType: 'address payable' },
        ],
        name: 'flushAddr',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'fromReferrs',
        inputs: [{ type: 'address', name: '', internalType: 'address' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'getDayUnixTime',
        inputs: [{ type: 'uint256', name: 'day', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'bool', name: '', internalType: 'bool' },
          { type: 'uint256', name: '', internalType: 'uint256' },
        ],
        name: 'getFirstAuction',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256', name: 'stakeReturn', internalType: 'uint256' },
          { type: 'uint256', name: 'payout', internalType: 'uint256' },
          { type: 'uint256', name: 'dividends', internalType: 'uint256' },
          { type: 'uint256', name: 'penalty', internalType: 'uint256' },
          { type: 'uint256', name: 'cappedPenalty', internalType: 'uint256' },
        ],
        name: 'getUnstakeParams',
        inputs: [
          { type: 'address', name: 'user', internalType: 'address' },
          { type: 'uint256', name: 'stakeIndex', internalType: 'uint256' },
          { type: 'uint40', name: 'stakeIdParam', internalType: 'uint40' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256[10]', name: '', internalType: 'uint256[10]' },
        ],
        name: 'globalInfo',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256', name: 'lockedSunsTotal', internalType: 'uint256' },
          {
            type: 'uint256',
            name: 'nextStakeSharesTotal',
            internalType: 'uint256',
          },
          { type: 'uint40', name: 'shareRate', internalType: 'uint40' },
          {
            type: 'uint256',
            name: 'stakePenaltyTotal',
            internalType: 'uint256',
          },
          { type: 'uint16', name: 'dailyDataCount', internalType: 'uint16' },
          {
            type: 'uint256',
            name: 'stakeSharesTotal',
            internalType: 'uint256',
          },
          { type: 'uint40', name: 'latestStakeId', internalType: 'uint40' },
        ],
        name: 'globals',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
        name: 'isOwner',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'jackpotReceivedAuction',
        inputs: [
          { type: 'uint256', name: '', internalType: 'uint256' },
          { type: 'address', name: '', internalType: 'address' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'lastEndedLoteryDay',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'lastEndedLoteryDayWithWinner',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'address', name: 'who', internalType: 'address' },
          { type: 'uint256', name: 'chanceCount', internalType: 'uint256' },
        ],
        name: 'loteryCount',
        inputs: [
          { type: 'uint256', name: '', internalType: 'uint256' },
          { type: 'uint256', name: '', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'loteryCountLen',
        inputs: [{ type: 'uint256', name: 'day', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'loteryDayWaitingForWinner',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'loteryDayWaitingForWinnerNew',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256', name: 'change', internalType: 'uint256' },
          { type: 'uint256', name: 'chanceCount', internalType: 'uint256' },
        ],
        name: 'loteryLobby',
        inputs: [
          { type: 'uint256', name: '', internalType: 'uint256' },
          { type: 'address', name: '', internalType: 'address' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'string', name: '', internalType: 'string' }],
        name: 'name',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'address', name: '', internalType: 'address' }],
        name: 'owner',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'ownerClaimFirstTwoDays',
        inputs: [],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'renounceOwnership',
        inputs: [],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'setDefaultReferrerAddr',
        inputs: [
          {
            type: 'address',
            name: '_defaultReferrerAddr',
            internalType: 'address',
          },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'setFlushAddr',
        inputs: [
          {
            type: 'address',
            name: '_flushAddr',
            internalType: 'address payable',
          },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'stakeCount',
        inputs: [
          { type: 'address', name: 'stakerAddr', internalType: 'address' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'stakeEnd',
        inputs: [
          { type: 'uint256', name: 'stakeIndex', internalType: 'uint256' },
          { type: 'uint40', name: 'stakeIdParam', internalType: 'uint40' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'stakeGoodAccounting',
        inputs: [
          { type: 'address', name: 'stakerAddr', internalType: 'address' },
          { type: 'uint256', name: 'stakeIndex', internalType: 'uint256' },
          { type: 'uint40', name: 'stakeIdParam', internalType: 'uint40' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint40', name: 'stakeId', internalType: 'uint40' },
          { type: 'uint256', name: 'stakedSuns', internalType: 'uint256' },
          { type: 'uint256', name: 'stakeShares', internalType: 'uint256' },
          { type: 'uint16', name: 'lockedDay', internalType: 'uint16' },
          { type: 'uint16', name: 'stakedDays', internalType: 'uint16' },
          { type: 'uint16', name: 'unlockedDay', internalType: 'uint16' },
        ],
        name: 'stakeLists',
        inputs: [
          { type: 'address', name: '', internalType: 'address' },
          { type: 'uint256', name: '', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'stakeStart',
        inputs: [
          { type: 'uint256', name: 'newStakedSuns', internalType: 'uint256' },
          { type: 'uint256', name: 'newStakedDays', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'string', name: '', internalType: 'string' }],
        name: 'symbol',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'totalSupply',
        inputs: [],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
        name: 'transfer',
        inputs: [
          { type: 'address', name: 'recipient', internalType: 'address' },
          { type: 'uint256', name: 'amount', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [{ type: 'bool', name: '', internalType: 'bool' }],
        name: 'transferFrom',
        inputs: [
          { type: 'address', name: 'sender', internalType: 'address' },
          { type: 'address', name: 'recipient', internalType: 'address' },
          { type: 'uint256', name: 'amount', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'transferOwnership',
        inputs: [
          { type: 'address', name: 'newOwner', internalType: 'address' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'pure',
        payable: false,
        outputs: [
          { type: 'uint256', name: '_waasLobby', internalType: 'uint256' },
        ],
        name: 'waasLobby',
        inputs: [
          { type: 'uint256', name: 'enterDay', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'whatDayIsItToday',
        inputs: [{ type: 'uint256', name: 'day', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'address', name: 'who', internalType: 'address payable' },
          { type: 'uint256', name: 'totalAmount', internalType: 'uint256' },
          { type: 'uint256', name: 'restAmount', internalType: 'uint256' },
        ],
        name: 'winners',
        inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'withdrawLotery',
        inputs: [{ type: 'uint256', name: 'day', internalType: 'uint256' }],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'xfFlush',
        inputs: [],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        name: 'xfLobby',
        inputs: [{ type: 'uint256', name: '', internalType: 'uint256' }],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'payable',
        payable: true,
        outputs: [],
        name: 'xfLobbyEnter',
        inputs: [
          { type: 'address', name: 'referrerAddr', internalType: 'address' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint256', name: 'rawAmount', internalType: 'uint256' },
          { type: 'address', name: 'referrerAddr', internalType: 'address' },
        ],
        name: 'xfLobbyEntry',
        inputs: [
          { type: 'address', name: 'memberAddr', internalType: 'address' },
          { type: 'uint256', name: 'enterDay', internalType: 'uint256' },
          { type: 'uint256', name: 'entryIndex', internalType: 'uint256' },
        ],
        constant: true,
      },
      {
        type: 'function',
        stateMutability: 'nonpayable',
        payable: false,
        outputs: [],
        name: 'xfLobbyExit',
        inputs: [
          { type: 'uint256', name: 'enterDay', internalType: 'uint256' },
          { type: 'uint256', name: 'count', internalType: 'uint256' },
        ],
        constant: false,
      },
      {
        type: 'function',
        stateMutability: 'view',
        payable: false,
        outputs: [
          { type: 'uint40', name: 'headIndex', internalType: 'uint40' },
          { type: 'uint40', name: 'tailIndex', internalType: 'uint40' },
        ],
        name: 'xfLobbyMembers',
        inputs: [
          { type: 'uint256', name: '', internalType: 'uint256' },
          { type: 'address', name: '', internalType: 'address' },
        ],
        constant: true,
      },
    ],
  },
};
